package main;
// offline Version funktioniert.
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public class SVGBuilder {

    public static String buildMultiColorSVG(Map<Color, String> colorPathMap) {
        System.out.println("\n=== BUILDING MULTICOLOR SVG ===");
        System.out.println("Eingabe: " + colorPathMap.size() + " Farbebenen");
        
        if (colorPathMap.isEmpty()) {
            System.out.println("❌ Keine Pfade zum Kombinieren vorhanden");
            return createEmptySVG();
        }

        // WICHTIGER DEBUG: Zeige alle Map-Einträge die ankommen
        System.out.println("EMPFANGENE MAP-INHALTE:");
        int receiveIndex = 0;
        for (Map.Entry<Color, String> entry : colorPathMap.entrySet()) {
            Color color = entry.getKey();
            String paths = entry.getValue();
            System.out.println("  Received[" + receiveIndex + "]: " + colorToString(color) + 
                             " (Hash: " + color.hashCode() + ") -> " + 
                             (paths != null ? paths.length() : 0) + " Zeichen");
            
            if (paths != null && paths.length() > 0) {
                // Zähle die Anzahl der Pfade
                int pathCount = countPaths(paths);
                System.out.println("    Enthält " + pathCount + " Pfad-Elemente");
                
                // Zeige ersten Pfad als Beispiel
                if (pathCount > 0) {
                    String firstLine = paths.split("\n")[0];
                    System.out.println("    Beispiel: " + (firstLine.length() > 80 ? firstLine.substring(0, 80) + "..." : firstLine));
                }
            }
            receiveIndex++;
        }

        StringBuilder finalSvg = new StringBuilder();
        
        // SVG-Header mit KORREKTEN Dimensionen von Potrace übernehmen
        // Alle Potrace-SVGs haben die gleichen Dimensionen, also nehme die erste
        String firstSvgPath = colorPathMap.values().iterator().next();
        ViewBoxInfo viewBoxInfo = extractViewBoxFromFirstEntry(colorPathMap);
        
        finalSvg.append("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n");
        finalSvg.append("<!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\" ");
        finalSvg.append("\"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\">\n");
        finalSvg.append("<svg version=\"1.0\" xmlns=\"http://www.w3.org/2000/svg\"\n");
        finalSvg.append(" width=\"").append(viewBoxInfo.width).append("\" height=\"").append(viewBoxInfo.height).append("\"\n");
        finalSvg.append(" viewBox=\"").append(viewBoxInfo.viewBox).append("\"\n");
        finalSvg.append(" preserveAspectRatio=\"xMidYMid meet\">\n");
        
        // Metadaten
        finalSvg.append("  <title>Multicolor Vectorized Image</title>\n");
        finalSvg.append("  <desc>Generated by Java Posterizer with Potrace - ");
        finalSvg.append(colorPathMap.size()).append(" colors</desc>\n\n");
        
        // WICHTIG: Füge die Potrace-Transformation hinzu
        finalSvg.append("  <g transform=\"").append(viewBoxInfo.transform).append("\">\n\n");

        // Sortiere Farben nach Helligkeit (dunkle zuerst = Hintergrund)
        List<Map.Entry<Color, String>> sortedEntries = new ArrayList<>(colorPathMap.entrySet());
        sortedEntries.sort((e1, e2) -> Double.compare(getColorBrightness(e1.getKey()), getColorBrightness(e2.getKey())));

        int validLayers = 0;
        int totalPathsAdded = 0;
        
        // Füge jede Farbe als separate Gruppe hinzu
        for (int i = 0; i < sortedEntries.size(); i++) {
            Map.Entry<Color, String> entry = sortedEntries.get(i);
            Color color = entry.getKey();
            String paths = entry.getValue();
            
            if (paths == null || paths.trim().isEmpty()) {
                System.out.println("⚠️  Überspringe leere Pfade für " + colorToString(color));
                continue;
            }

            String hex = colorToHex(color);
            String groupId = "color-layer-" + i;
            double brightness = getColorBrightness(color);
            
            System.out.println("✅ Füge Farbebene " + (i+1) + " hinzu: " + colorToString(color) + 
                             " (Helligkeit: " + String.format("%.1f", brightness) + ")");
            System.out.println("   Rohdaten: " + paths.length() + " Zeichen");
            
            finalSvg.append("    <!-- Farbebene ").append(i+1).append(": ").append(colorToString(color)).append(" -->\n");
            finalSvg.append("    <g id=\"").append(groupId).append("\" ");
            finalSvg.append("fill=\"").append(hex).append("\" ");
            finalSvg.append("stroke=\"none\">\n");
            
            // EINFACH EINFÜGEN: Keine Validierung, einfach alle Pfade rein
            String[] lines = paths.split("\n");
            int pathsAddedThisColor = 0;
            
            for (String line : lines) {
                String trimmedLine = line.trim();
                if (!trimmedLine.isEmpty()) {
                    // Einfach einrücken und einfügen - keine Validierung
                    finalSvg.append("      ").append(trimmedLine).append("\n");
                    pathsAddedThisColor++;
                }
            }
            
            finalSvg.append("    </g>\n\n");
            validLayers++;
            totalPathsAdded += pathsAddedThisColor;
            
            System.out.println("    → " + pathsAddedThisColor + " Zeilen eingefügt");
        }

        // Schließe die Transform-Gruppe
        finalSvg.append("  </g>\n");
        finalSvg.append("</svg>");
        
        String result = finalSvg.toString();
        
        System.out.println("🎨 MULTICOLOR SVG ERSTELLT:");
        System.out.println("   - Dateigröße: " + result.length() + " Zeichen");
        System.out.println("   - Gültige Farbebenen: " + validLayers + "/" + colorPathMap.size());
        System.out.println("   - Gesamte Zeilen eingefügt: " + totalPathsAdded);
        
        // Zähle path-Elemente im finalen SVG
        int finalPathCount = countTotalPaths(result);
        System.out.println("   - Tatsächliche path-Elemente: " + finalPathCount);
        
        if (validLayers == 0) {
            System.out.println("❌ WARNUNG: Keine gültigen Farbebenen im finalen SVG!");
            return createEmptySVG();
        }
        
        if (finalPathCount == 0) {
            System.out.println("❌ WARNUNG: Keine path-Elemente im finalen SVG!");
            System.out.println("   Debug: Erste 500 Zeichen des SVG:");
            System.out.println(result.substring(0, Math.min(500, result.length())));
        }
        
        System.out.println("=== SVG BUILD COMPLETE ===\n");
        return result;
    }

    private static int countPaths(String svgContent) {
        if (svgContent == null) return 0;
        
        int count = 0;
        String[] lines = svgContent.split("\n");
        for (String line : lines) {
            if (line.trim().startsWith("<path") && line.contains("d=")) {
                count++;
            }
        }
        return count;
    }

    private static int countTotalPaths(String svgContent) {
        if (svgContent == null) return 0;
        
        int count = 0;
        String[] lines = svgContent.split("\n");
        for (String line : lines) {
            if (line.trim().startsWith("<path") && line.contains("d=")) {
                count++;
            }
        }
        return count;
    }

    private static double getColorBrightness(Color color) {
        // Berechne die wahrgenommene Helligkeit (Luminanz)
        return 0.299 * color.getRed() + 0.587 * color.getGreen() + 0.114 * color.getBlue();
    }

    private static String colorToString(Color c) {
        return ColorUtils.colorToString(c);
    }

    private static String colorToHex(Color c) {
        return ColorUtils.colorToHex(c);
    }

    private static ViewBoxInfo extractViewBoxFromFirstEntry(Map<Color, String> colorPathMap) {
        // Da alle Potrace-SVGs die gleichen Dimensionen haben, müssen wir die Original-SVG-Daten rekonstruieren
        // Basierend auf der Debug-Ausgabe verwenden alle die gleiche Struktur
        ViewBoxInfo info = new ViewBoxInfo();
        info.width = "983.000000pt";
        info.height = "709.000000pt"; 
        info.viewBox = "0 0 983.000000 709.000000";
        info.transform = "translate(0.000000,709.000000) scale(0.100000,-0.100000)";
        
        System.out.println("📐 ViewBox-Info extrahiert:");
        System.out.println("   Width: " + info.width);
        System.out.println("   Height: " + info.height);
        System.out.println("   ViewBox: " + info.viewBox);
        System.out.println("   Transform: " + info.transform);
        
        return info;
    }

    private static class ViewBoxInfo {
        String width = "100%";
        String height = "100%";
        String viewBox = "0 0 1000 1000";
        String transform = "";
    }

    private static String createEmptySVG() {
        return "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n" +
               "<svg width=\"200\" height=\"200\" viewBox=\"0 0 200 200\" " +
               "xmlns=\"http://www.w3.org/2000/svg\" version=\"1.1\">\n" +
               "  <title>Empty SVG - No Paths Found</title>\n" +
               "  <rect width=\"100%\" height=\"100%\" fill=\"#f0f0f0\" stroke=\"#ccc\"/>\n" +
               "  <text x=\"100\" y=\"100\" text-anchor=\"middle\" fill=\"#666\" " +
               "font-family=\"Arial, sans-serif\" font-size=\"12\">" +
               "No vector paths found</text>\n" +
               "</svg>";
    }

    public static void saveToFile(String svgContent, File file) {
        try (PrintWriter out = new PrintWriter(file, "UTF-8")) {
            out.write(svgContent);
            
            int pathCount = countTotalPaths(svgContent);
            System.out.println("💾 SVG gespeichert: " + file.getAbsolutePath());
            System.out.println("   - Dateigröße: " + svgContent.length() + " Zeichen");
            System.out.println("   - Path-Elemente: " + pathCount);
            
            if (pathCount == 0) {
                System.out.println("⚠️  WARNUNG: Gespeicherte SVG enthält keine Pfade!");
            } else {
                System.out.println("✅ SVG mit " + pathCount + " Pfaden erfolgreich gespeichert!");
            }
            
        } catch (IOException e) {
            System.out.println("❌ Fehler beim Speichern der SVG-Datei: " + e.getMessage());
            e.printStackTrace();
        }
    }
}